import Head from 'next/head'
import {Navbar} from '../../components/Navbar'
import '../styles/globals.css'
import '../styles/Home.module.css'
import './_document.js'

// import { Inter } from 'next/font/google'
// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>REM Rendezvous</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

      <Navbar/>

      </main>
    </>
  )
}
