DROP DATABASE IF EXISTS rem_db;
CREATE DATABASE rem_db;
USE rem_db;

CREATE TABLE users (
  id INT NOT NULL AUTO_INCREMENT,
  text VARCHAR(255) NOT NULL,
  hasAnAccount BOOLEAN NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
);