DROP DATABASE IF EXISTS rem_api;
CREATE DATABASE rem_api;

USE rem_api;

CREATE TABLE user (
  id INT NOT NULL AUTO_INCREMENT,
  text VARCHAR(255) NOT NULL,
  hasAnAccount BOOLEAN NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
);